 language: java
 jdk: openjdk13
 script:  
   - ./backend/gradlew clean  cucumberTest
   - ./backend/gradlew clean  check
   - ./backend//gradlew jacocoTestReport
   - ./backend//gradlew sonarqube
   - ./backend//gradlew javadocs
